import { AlbertaAttraction } from './alberta-attractions';

// Alberta's Best Waterfalls
export const ALBERTA_WATERFALLS: AlbertaAttraction[] = [
  {
    id: 'wf1',
    name: 'Athabasca Falls',
    location: 'Jasper National Park',
    coordinates: { lat: 52.6667, lng: -117.8833 },
    description: 'Powerful waterfall where the Athabasca River is forced through a narrow gorge.',
    category: 'waterfall',
    season: 'Year-round',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop',
    rating: 4.7,
    priceRange: 'free',
    duration: '1-2 hours',
    features: ['Powerful waterfall', 'Easy access', 'Viewing platforms', 'Photography'],
    nearestCity: 'Jasper',
    distanceFromCalgary: '4 hours',
    distanceFromEdmonton: '3.5 hours',
    isHidden: false,
    dangerousAnimals: ['Black bears', 'Grizzly bears'],
    safetyWarnings: ['Stay on designated trails', 'Keep away from cliff edges', 'Slippery rocks when wet'],
    tips: ['Best flow in spring/early summer', 'Multiple viewpoints available', 'Combine with Sunwapta Falls']
  },
  {
    id: 'wf2',
    name: 'Takakkaw Falls',
    location: 'Yoho National Park',
    coordinates: { lat: 51.4500, lng: -116.4833 },
    description: "One of Canada's highest waterfalls at 373 meters, fed by Daly Glacier.",
    category: 'waterfall',
    season: 'June - October',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&h=300&fit=crop',
    rating: 4.9,
    priceRange: 'free',
    duration: '2-3 hours',
    features: ['Tallest waterfall', 'Glacier-fed', 'Mist spray', 'Alpine setting'],
    nearestCity: 'Field, BC',
    distanceFromCalgary: '3.5 hours',
    distanceFromEdmonton: '5 hours',
    isHidden: false,
    dangerousAnimals: ['Black bears', 'Grizzly bears', 'Mountain goats'],
    safetyWarnings: ['Road may be closed in winter', 'Rockfall danger', 'Cold mist spray'],
    bestTimeToVisit: 'Early morning for best light',
    tips: ['Bring rain jacket for mist', 'Peak flow in June-July', 'Road closes in winter']
  },
  {
    id: 'wf3',
    name: 'Sunwapta Falls',
    location: 'Jasper National Park',
    coordinates: { lat: 52.5833, lng: -117.6500 },
    description: 'Multi-tiered waterfall with upper and lower falls accessible by short walks.',
    category: 'waterfall',
    season: 'Year-round',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop',
    rating: 4.6,
    priceRange: 'free',
    duration: '1-3 hours',
    features: ['Multi-tiered falls', 'Upper and lower viewpoints', 'Easy walks', 'Turquoise pools'],
    nearestCity: 'Jasper',
    distanceFromCalgary: '4 hours',
    distanceFromEdmonton: '3.5 hours',
    isHidden: false,
    dangerousAnimals: ['Black bears', 'Grizzly bears'],
    safetyWarnings: ['Steep canyon edges', 'Slippery rocks', 'Fast-moving water'],
    tips: ['Visit both upper and lower falls', 'Better in spring for water flow', 'Great for photography']
  },
  {
    id: 'wf4',
    name: 'Lundbreck Falls',
    location: 'Southern Alberta',
    coordinates: { lat: 49.5833, lng: -113.8667 },
    description: 'Hidden gem waterfall on the Crowsnest River with swimming holes and picnic areas.',
    category: 'waterfall',
    season: 'May - October',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&h=300&fit=crop',
    rating: 4.4,
    priceRange: 'free',
    duration: '2-4 hours',
    features: ['Swimming holes', 'Picnic areas', 'Easy access', 'Family-friendly'],
    nearestCity: 'Pincher Creek',
    distanceFromCalgary: '2.5 hours',
    distanceFromEdmonton: '4.5 hours',
    isHidden: true,
    safetyWarnings: ['Swift current', 'Cold water', 'Slippery rocks'],
    tips: ['Great for swimming in summer', 'Bring picnic lunch', 'Popular with locals']
  },
  {
    id: 'wf5',
    name: 'Crescent Falls',
    location: 'David Thompson Highway',
    coordinates: { lat: 52.1167, lng: -116.2833 },
    description: 'Spectacular crescent-shaped waterfall with multiple tiers and turquoise pools.',
    category: 'waterfall',
    season: 'May - October',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop',
    rating: 4.8,
    priceRange: 'free',
    duration: '2-3 hours',
    features: ['Crescent shape', 'Multiple tiers', 'Turquoise pools', 'Photography'],
    nearestCity: 'Nordegg',
    distanceFromCalgary: '3 hours',
    distanceFromEdmonton: '2.5 hours',
    isHidden: true,
    dangerousAnimals: ['Black bears', 'Grizzly bears', 'Cougars'],
    safetyWarnings: ['Steep canyon walls', 'Loose rocks', 'Remote location'],
    tips: ['Moderate hike required', 'Best in spring for water flow', 'Bring bear spray']
  },
  {
    id: 'wf6',
    name: 'Tangle Creek Falls',
    location: 'Icefields Parkway',
    coordinates: { lat: 52.2833, lng: -117.2167 },
    description: 'Striking multi-tiered waterfall visible right from the Icefields Parkway—just steps from the road.',
    category: 'waterfall',
    season: 'Year-round',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&h=300&fit=crop',
    rating: 4.5,
    priceRange: 'free',
    duration: '30 minutes',
    features: ['Roadside access', 'Multi-tiered', 'Easy viewing', 'Photography'],
    nearestCity: 'Jasper',
    distanceFromCalgary: '4 hours',
    distanceFromEdmonton: '3.5 hours',
    isHidden: false,
    dangerousAnimals: ['Black bears', 'Grizzly bears'],
    safetyWarnings: ['Traffic on highway', 'Slippery rocks'],
    tips: ['Perfect roadside stop', 'Great for quick photos', 'Visible from parking area']
  },
  {
    id: 'wf7',
    name: 'Panther Falls',
    location: 'Banff National Park',
    coordinates: { lat: 52.1833, lng: -117.1833 },
    description: 'A 25m veiling plunge along Nigel Creek, a half-kilometre hike from the Icefields Parkway.',
    category: 'waterfall',
    season: 'June - September',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop',
    rating: 4.6,
    priceRange: 'free',
    duration: '1 hour',
    features: ['Veiling waterfall', 'Short hike', 'Nigel Creek', 'Mountain views'],
    nearestCity: 'Jasper',
    distanceFromCalgary: '4 hours',
    distanceFromEdmonton: '3.5 hours',
    isHidden: false,
    dangerousAnimals: ['Black bears', 'Grizzly bears'],
    safetyWarnings: ['Creek crossing', 'Wet rocks'],
    tips: ['Easy half-km hike', 'Best flow in early summer', 'Great photography spot']
  },
  {
    id: 'wf8',
    name: 'Bow Falls',
    location: 'Banff',
    coordinates: { lat: 51.1667, lng: -115.5667 },
    description: 'In the heart of Banff town, this broad, powerful cascade is highly accessible and perfect for a quick stop.',
    category: 'waterfall',
    season: 'Year-round',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&h=300&fit=crop',
    rating: 4.3,
    priceRange: 'free',
    duration: '30 minutes - 1 hour',
    features: ['Urban waterfall', 'Easy access', 'Broad cascade', 'Town views'],
    nearestCity: 'Banff',
    distanceFromCalgary: '1.5 hours',
    distanceFromEdmonton: '4.5 hours',
    isHidden: false,
    accessibility: 'Wheelchair accessible viewing areas',
    tips: ['Walking distance from downtown', 'Great for families', 'Popular photo spot']
  },
  {
    id: 'wf9',
    name: 'Siffleur Falls',
    location: 'David Thompson Country',
    coordinates: { lat: 52.0833, lng: -116.4167 },
    description: 'Nestled in David Thompson country, this 3.5km trail leads to falls cascading into a canyon through forest scenery.',
    category: 'waterfall',
    season: 'June - September',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop',
    rating: 4.7,
    priceRange: 'free',
    duration: '2-3 hours',
    features: ['Canyon falls', 'Forest trail', 'Suspension bridge', 'Remote location'],
    nearestCity: 'Nordegg',
    distanceFromCalgary: '3 hours',
    distanceFromEdmonton: '2.5 hours',
    isHidden: true,
    dangerousAnimals: ['Black bears', 'Grizzly bears', 'Cougars'],
    safetyWarnings: ['Remote trail', 'Canyon edges', 'Bridge crossing'],
    tips: ['3.5km hike required', 'Suspension bridge crossing', 'Bring bear spray']
  },
  {
    id: 'wf10',
    name: 'Ram Falls',
    location: 'David Thompson Country',
    coordinates: { lat: 52.4000, lng: -116.0667 },
    description: 'This 20m drop into the Ram River Canyon offers tranquility and occasional wildlife viewing.',
    category: 'waterfall',
    season: 'May - October',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&h=300&fit=crop',
    rating: 4.5,
    priceRange: 'free',
    duration: '1-2 hours',
    features: ['Canyon waterfall', 'Wildlife viewing', 'Viewing platform', 'Peaceful setting'],
    nearestCity: 'Nordegg',
    distanceFromCalgary: '3 hours',
    distanceFromEdmonton: '2.5 hours',
    isHidden: false,
    dangerousAnimals: ['Black bears', 'Grizzly bears'],
    safetyWarnings: ['Canyon edges', 'Wet stairs'],
    accessibility: 'Stairway to viewing platform',
    tips: ['Viewing platform available', 'Good for wildlife spotting', 'Less crowded than other falls']
  },
  {
    id: 'wf11',
    name: 'Stanley Falls',
    location: 'Jasper National Park',
    coordinates: { lat: 52.2000, lng: -117.2500 },
    description: 'A 12m waterfall off the Columbia Icefields Parkway via a 3.9km Beauty Creek trail.',
    category: 'waterfall',
    season: 'July - September',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop',
    rating: 4.4,
    priceRange: 'free',
    duration: '3-4 hours',
    features: ['Beauty Creek trail', 'Remote waterfall', 'Alpine setting', 'Moderate hike'],
    nearestCity: 'Jasper',
    distanceFromCalgary: '4 hours',
    distanceFromEdmonton: '3.5 hours',
    isHidden: true,
    dangerousAnimals: ['Black bears', 'Grizzly bears'],
    safetyWarnings: ['Remote trail', 'Creek crossings', 'Weather dependent'],
    tips: ['3.9km hike required', 'Follow Beauty Creek trail', 'Best in mid-summer']
  },
  {
    id: 'wf12',
    name: 'Blakiston Falls',
    location: 'Waterton Lakes National Park',
    coordinates: { lat: 49.0500, lng: -113.9167 },
    description: 'Located in Waterton Lakes National Park, this 20m waterfall is reached via a short family-friendly trail.',
    category: 'waterfall',
    season: 'May - October',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&h=300&fit=crop',
    rating: 4.6,
    priceRange: 'free',
    duration: '1-2 hours',
    features: ['Family-friendly', 'Short trail', 'Viewing platform', 'Mountain backdrop'],
    nearestCity: 'Waterton Park',
    distanceFromCalgary: '3.5 hours',
    distanceFromEdmonton: '6 hours',
    isHidden: false,
    dangerousAnimals: ['Black bears', 'Grizzly bears'],
    accessibility: 'Family-friendly trail and viewing platform',
    tips: ['Easy family hike', 'Great for kids', 'Combine with other Waterton activities']
  },
  {
    id: 'wf13',
    name: 'Cameron Falls',
    location: 'Waterton Lakes National Park',
    coordinates: { lat: 49.0500, lng: -113.9000 },
    description: 'Right in Waterton Lakes National Park, this picturesque fall is highly accessible and scenic year-round.',
    category: 'waterfall',
    season: 'Year-round',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop',
    rating: 4.4,
    priceRange: 'free',
    duration: '30 minutes - 1 hour',
    features: ['Highly accessible', 'Year-round', 'Picturesque', 'Town proximity'],
    nearestCity: 'Waterton Park',
    distanceFromCalgary: '3.5 hours',
    distanceFromEdmonton: '6 hours',
    isHidden: false,
    accessibility: 'Very accessible, close to town',
    tips: ['Walking distance from town', 'Beautiful in all seasons', 'Great photo opportunities']
  },
  {
    id: 'wf14',
    name: 'Elbow Falls',
    location: 'Kananaskis Country',
    coordinates: { lat: 50.9500, lng: -114.6000 },
    description: 'Just west of Bragg Creek in Kananaskis, these small but beautiful falls are great for picnics and short walks.',
    category: 'waterfall',
    season: 'Year-round',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&h=300&fit=crop',
    rating: 4.3,
    priceRange: 'free',
    duration: '1-2 hours',
    features: ['Picnic areas', 'Short walks', 'Family-friendly', 'Swimming holes'],
    nearestCity: 'Bragg Creek',
    distanceFromCalgary: '45 minutes',
    distanceFromEdmonton: '3.5 hours',
    isHidden: false,
    accessibility: 'Easy access with picnic facilities',
    tips: ['Great for families', 'Popular picnic spot', 'Swimming in summer']
  },
  {
    id: 'wf15',
    name: 'Sheep River Falls',
    location: 'Kananaskis Country',
    coordinates: { lat: 50.6833, lng: -114.4167 },
    description: 'Near Turner Valley in Kananaskis—an impressive 10m drop in a rugged gorge with easy access.',
    category: 'waterfall',
    season: 'Year-round',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop',
    rating: 4.4,
    priceRange: 'free',
    duration: '1-2 hours',
    features: ['Rugged gorge', 'Easy access', '10m drop', 'Rocky canyon'],
    nearestCity: 'Turner Valley',
    distanceFromCalgary: '1 hour',
    distanceFromEdmonton: '4 hours',
    isHidden: false,
    safetyWarnings: ['Steep gorge edges', 'Slippery rocks'],
    tips: ['Easy roadside access', 'Impressive gorge setting', 'Good for photography']
  },
  {
    id: 'wf16',
    name: 'Kakwa Falls',
    location: 'Kakwa Wildland Provincial Park',
    coordinates: { lat: 54.0000, lng: -119.5000 },
    description: "Alberta's tallest waterfall at around 30m, located in Kakwa Wildland Provincial Park. Accessible via a challenging 21km hike.",
    category: 'waterfall',
    difficulty: 'expert',
    season: 'July - September',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop',
    rating: 4.9,
    priceRange: 'free',
    duration: '2-3 days',
    features: ['Tallest in Alberta', 'Remote wilderness', 'Multi-day hike', 'Pristine nature'],
    nearestCity: 'Grande Prairie',
    distanceFromCalgary: '6 hours',
    distanceFromEdmonton: '4 hours',
    isHidden: true,
    dangerousAnimals: ['Grizzly bears', 'Black bears', 'Wolves'],
    safetyWarnings: ['Extremely remote', 'Multi-day commitment', 'Weather dependent'],
    tips: ['Experienced hikers only', 'Overnight camping required', 'Bring satellite communication']
  },
  {
    id: 'wf17',
    name: 'Vermilion Falls',
    location: 'Peace River, Northern Alberta',
    coordinates: { lat: 56.2333, lng: -117.2833 },
    description: 'On the Peace River in northern Alberta, this extremely wide cascaded step is the second-largest waterfall in Canada by flow rate.',
    category: 'waterfall',
    season: 'Year-round',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&h=300&fit=crop',
    rating: 4.7,
    priceRange: 'free',
    duration: '2-4 hours',
    features: ['Massive flow rate', 'Wide cascade', 'Peace River', 'Northern wilderness'],
    nearestCity: 'Peace River',
    distanceFromCalgary: '6 hours',
    distanceFromEdmonton: '3 hours',
    isHidden: true,
    dangerousAnimals: ['Black bears', 'Wolves'],
    safetyWarnings: ['Remote northern location', 'Strong river current'],
    tips: ['Second-largest by flow in Canada', 'Remote northern adventure', 'Best accessed by boat']
  },
  {
    id: 'wf18',
    name: 'Bridal Veil Falls',
    location: 'Banff National Park',
    coordinates: { lat: 52.1667, lng: -117.1667 },
    description: 'A spectacular, high (~1200 ft) horsetail-plunge waterfall draining from Huntington Glacier into Nigel Creek.',
    category: 'waterfall',
    difficulty: 'difficult',
    season: 'July - September',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop',
    rating: 4.8,
    priceRange: 'free',
    duration: '6-8 hours',
    features: ['1200ft drop', 'Glacier-fed', 'Horsetail plunge', 'Remote viewing'],
    nearestCity: 'Jasper',
    distanceFromCalgary: '4 hours',
    distanceFromEdmonton: '3.5 hours',
    isHidden: true,
    dangerousAnimals: ['Grizzly bears', 'Black bears'],
    safetyWarnings: ['Extremely high elevation', 'Glacier terrain', 'Weather dependent'],
    tips: ['Advanced hiking required', 'Best viewed from distance', 'Spectacular glacier views']
  }
];

// Bird Watching Hotspots
export const ALBERTA_BIRDWATCHING_SPOTS: AlbertaAttraction[] = [
  {
    id: 'bw1',
    name: 'Inglewood Bird Sanctuary',
    location: 'Calgary',
    coordinates: { lat: 51.0333, lng: -114.0167 },
    description: 'Urban oasis with over 270 bird species along the Bow River floodplain.',
    category: 'birdwatching',
    season: 'Year-round',
    image: 'https://images.unsplash.com/photo-1444927714506-8492d94b5ba0?w=400&h=300&fit=crop',
    rating: 4.6,
    priceRange: 'free',
    duration: '2-4 hours',
    features: ['270+ bird species', 'Nature trails', 'Visitor center', 'Guided tours'],
    nearestCity: 'Calgary',
    distanceFromCalgary: '15 minutes',
    distanceFromEdmonton: '3 hours',
    isHidden: false,
    bestTimeToVisit: 'Early morning or late afternoon',
    accessibility: 'Wheelchair accessible trails available',
    tips: ['Bring binoculars', 'Best birding in spring migration', 'Free guided tours available']
  },
  {
    id: 'bw2',
    name: 'Elk Island National Park',
    location: 'Near Edmonton',
    coordinates: { lat: 53.6167, lng: -112.8667 },
    description: 'Boreal forest and wetlands home to over 250 bird species including trumpeter swans.',
    category: 'birdwatching',
    season: 'Year-round',
    image: 'https://images.unsplash.com/photo-1444927714506-8492d94b5ba0?w=400&h=300&fit=crop',
    rating: 4.7,
    priceRange: '$',
    duration: 'Half day - Full day',
    features: ['250+ bird species', 'Trumpeter swans', 'Boreal forest', 'Wetlands'],
    nearestCity: 'Edmonton',
    distanceFromCalgary: '3.5 hours',
    distanceFromEdmonton: '45 minutes',
    isHidden: false,
    dangerousAnimals: ['Bison', 'Black bears', 'Elk'],
    safetyWarnings: ['Keep distance from bison', 'Stay in vehicle in bison areas', 'Bears active in berry season'],
    bestTimeToVisit: 'May-June for spring migration',
    tips: ['Astotin Lake area best for waterfowl', 'Bring telephoto lens', 'Check for bison on roads']
  },
  {
    id: 'bw3',
    name: 'Frank Lake',
    location: 'High River',
    coordinates: { lat: 50.5167, lng: -113.8833 },
    description: 'Premier waterfowl viewing area with over 200 species and excellent facilities.',
    category: 'birdwatching',
    season: 'April - October',
    image: 'https://images.unsplash.com/photo-1444927714506-8492d94b5ba0?w=400&h=300&fit=crop',
    rating: 4.8,
    priceRange: 'free',
    duration: '2-6 hours',
    features: ['200+ bird species', 'Waterfowl viewing', 'Observation blinds', 'Photography blinds'],
    nearestCity: 'High River',
    distanceFromCalgary: '1 hour',
    distanceFromEdmonton: '4 hours',
    isHidden: true,
    bestTimeToVisit: 'Spring and fall migration',
    accessibility: 'Accessible viewing areas',
    tips: ['Peak migration in May and September', 'Bring spotting scope', 'Early morning best']
  },
  {
    id: 'bw4',
    name: 'Beaverhill Lake',
    location: 'East of Edmonton',
    coordinates: { lat: 53.4167, lng: -112.5167 },
    description: 'Important Bird Area with over 280 species, famous for shorebird migration.',
    category: 'birdwatching',
    season: 'April - October',
    image: 'https://images.unsplash.com/photo-1444927714506-8492d94b5ba0?w=400&h=300&fit=crop',
    rating: 4.9,
    priceRange: 'free',
    duration: 'Half day - Full day',
    features: ['280+ bird species', 'Shorebird migration', 'Nature center', 'Research station'],
    nearestCity: 'Tofield',
    distanceFromCalgary: '3.5 hours',
    distanceFromEdmonton: '1 hour',
    isHidden: true,
    bestTimeToVisit: 'May and August for shorebirds',
    tips: ['World-class shorebird viewing', 'Beaverhill Bird Observatory on site', 'Bring rubber boots']
  },
  {
    id: 'bw5',
    name: 'Weaselhead Flats',
    location: 'Calgary (Glenmore Reservoir)',
    coordinates: { lat: 50.9797, lng: -114.1127 },
    description: 'Riparian delta with mixed habitats that attract warblers, owls, and waterfowl.',
    category: 'birdwatching',
    season: 'April - October',
    image: 'https://images.unsplash.com/photo-1465101162946-4377e57745c3?w=400&h=300&fit=crop',
    rating: 4.6,
    priceRange: 'free',
    duration: '2-4 hours',
    features: ['Warblers', 'Owls', 'Observation points', 'Boardwalks'],
    nearestCity: 'Calgary',
    distanceFromCalgary: '20 minutes',
    distanceFromEdmonton: '3 hours',
    isHidden: true,
    bestTimeToVisit: 'May-June for songbirds',
    tips: ['Dawn is best', 'Stay on trails to protect habitat']
  },
  {
    id: 'bw6',
    name: 'Fish Creek Provincial Park',
    location: 'Calgary (South)',
    coordinates: { lat: 50.9219, lng: -114.0336 },
    description: 'One of Canada’s largest urban parks with rich riparian birdlife along Fish Creek.',
    category: 'birdwatching',
    season: 'Year-round',
    image: 'https://images.unsplash.com/photo-1452570053594-1b985d6ea890?w=400&h=300&fit=crop',
    rating: 4.7,
    priceRange: 'free',
    duration: '2-6 hours',
    features: ['Riparian habitat', 'Woodpeckers', 'Raptors', 'Multi-use trails'],
    nearestCity: 'Calgary',
    distanceFromCalgary: '0 km',
    distanceFromEdmonton: '3 hours',
    isHidden: false,
    tips: ['Scan river edges for herons', 'Winter owl sightings possible']
  },
  {
    id: 'bw7',
    name: 'Police Point Park',
    location: 'Medicine Hat',
    coordinates: { lat: 50.0469, lng: -110.6442 },
    description: 'Cottonwood forest on the South Saskatchewan River; great for migrants and resident birds.',
    category: 'birdwatching',
    season: 'April - October',
    image: 'https://images.unsplash.com/photo-1501706362039-c06b2d715385?w=400&h=300&fit=crop',
    rating: 4.5,
    priceRange: 'free',
    duration: '2-4 hours',
    features: ['Cottonwood forest', 'River views', 'Nature centre', 'Migration hotspot'],
    nearestCity: 'Medicine Hat',
    distanceFromCalgary: '3 hours',
    distanceFromEdmonton: '5 hours',
    isHidden: true,
    tips: ['Check river trails', 'Bring insect repellent in June']
  }
];

// Hidden Rivers and Lakes
export const ALBERTA_HIDDEN_WATERS: AlbertaAttraction[] = [
  {
    id: 'hw1',
    name: 'Elbow River - Bragg Creek',
    location: 'Bragg Creek',
    coordinates: { lat: 50.9833, lng: -114.6167 },
    description: 'Crystal clear mountain river perfect for fly fishing, swimming, and peaceful walks.',
    category: 'river',
    season: 'May - October',
    image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=400&h=300&fit=crop',
    rating: 4.5,
    priceRange: 'free',
    duration: '2-6 hours',
    features: ['Crystal clear water', 'Fly fishing', 'Swimming holes', 'Riverside trails'],
    nearestCity: 'Bragg Creek',
    distanceFromCalgary: '45 minutes',
    distanceFromEdmonton: '3.5 hours',
    isHidden: true,
    dangerousAnimals: ['Black bears', 'Cougars'],
    safetyWarnings: ['Swift current in spring', 'Cold water year-round', 'Wildlife in area'],
    tips: ['Great for trout fishing', 'Popular swimming spots', 'Bring bear spray']
  },
  {
    id: 'hw2',
    name: 'Spray Lakes Reservoir',
    location: 'Kananaskis Country',
    coordinates: { lat: 50.9167, lng: -115.3167 },
    description: 'Stunning turquoise reservoir surrounded by dramatic mountain peaks.',
    category: 'lake',
    season: 'June - October',
    image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=400&h=300&fit=crop',
    rating: 4.7,
    priceRange: 'free',
    duration: '2-8 hours',
    features: ['Turquoise water', 'Mountain reflections', 'Windsurfing', 'Photography'],
    nearestCity: 'Canmore',
    distanceFromCalgary: '1.5 hours',
    distanceFromEdmonton: '4.5 hours',
    isHidden: true,
    dangerousAnimals: ['Grizzly bears', 'Black bears'],
    safetyWarnings: ['Strong winds possible', 'Cold water', 'Remote location'],
    tips: ['Popular with windsurfers', 'Spectacular mountain views', 'Can be very windy']
  },
  {
    id: 'hw3',
    name: 'Kananaskis River',
    location: 'Kananaskis Country',
    coordinates: { lat: 50.7667, lng: -115.0833 },
    description: 'Wild mountain river with excellent whitewater rafting and pristine fishing.',
    category: 'river',
    season: 'May - September',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&h=300&fit=crop',
    rating: 4.6,
    priceRange: 'free',
    duration: '3-8 hours',
    features: ['Whitewater rafting', 'Fly fishing', 'Scenic canyon', 'Wildlife viewing'],
    nearestCity: 'Canmore',
    distanceFromCalgary: '1.5 hours',
    distanceFromEdmonton: '4.5 hours',
    isHidden: true,
    dangerousAnimals: ['Grizzly bears', 'Black bears', 'Cougars'],
    safetyWarnings: ['Fast-moving water', 'Cold temperatures', 'Remote sections'],
    tips: ['Excellent trout fishing', 'Rafting tours available', 'Bring warm clothes']
  },
  {
    id: 'hw4',
    name: 'Barrier Lake',
    location: 'Kananaskis Country',
    coordinates: { lat: 51.0333, lng: -115.0500 },
    description: 'Peaceful mountain lake with easy access and stunning Three Sisters views.',
    category: 'lake',
    season: 'Year-round',
    image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=400&h=300&fit=crop',
    rating: 4.4,
    priceRange: 'free',
    duration: '1-4 hours',
    features: ['Mountain views', 'Easy access', 'Picnic areas', 'Photography'],
    nearestCity: 'Canmore',
    distanceFromCalgary: '1.5 hours',
    distanceFromEdmonton: '4.5 hours',
    isHidden: false,
    accessibility: 'Wheelchair accessible areas',
    tips: ['Great for families', 'Beautiful Three Sisters views', 'Good picnic spot']
  }
];

// Food Trucks and Hidden Food Gems
export const ALBERTA_FOOD_TRUCKS: AlbertaAttraction[] = [
  {
    id: 'ft1',
    name: 'Tubby Dog Food Truck',
    location: 'Calgary (Various Locations)',
    coordinates: { lat: 51.0447, lng: -114.0719 },
    description: 'Iconic Calgary food truck serving gourmet hot dogs with creative toppings.',
    category: 'foodtruck',
    season: 'April - October',
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400&h=300&fit=crop',
    rating: 4.5,
    priceRange: '$',
    duration: '30 minutes',
    features: ['Gourmet hot dogs', 'Creative toppings', 'Local favorite', 'Instagram-worthy'],
    nearestCity: 'Calgary',
    distanceFromCalgary: 'Various locations',
    distanceFromEdmonton: '3 hours',
    isHidden: false,
    tips: ['Check social media for locations', 'Try the Mac Attack dog', 'Cash and card accepted']
  },
  {
    id: 'ft2',
    name: 'Drift Food Truck',
    location: 'Canmore',
    coordinates: { lat: 51.0918, lng: -115.3441 },
    description: 'Mountain town food truck specializing in fresh, local ingredients and craft coffee.',
    category: 'foodtruck',
    season: 'May - September',
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400&h=300&fit=crop',
    rating: 4.7,
    priceRange: '$$',
    duration: '30-60 minutes',
    features: ['Local ingredients', 'Craft coffee', 'Mountain views', 'Healthy options'],
    nearestCity: 'Canmore',
    distanceFromCalgary: '1.5 hours',
    distanceFromEdmonton: '4.5 hours',
    isHidden: true,
    tips: ['Perfect after hiking', 'Great breakfast burritos', 'Outdoor seating available']
  },
  {
    id: 'ft3',
    name: 'Prairie Smoke & Spice',
    location: 'Edmonton (Various Events)',
    coordinates: { lat: 53.5444, lng: -113.4909 },
    description: 'Award-winning BBQ food truck serving authentic Alberta beef and pork.',
    category: 'foodtruck',
    season: 'April - October',
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400&h=300&fit=crop',
    rating: 4.8,
    priceRange: '$$',
    duration: '30-45 minutes',
    features: ['Award-winning BBQ', 'Alberta beef', 'Authentic flavors', 'Competition-style'],
    nearestCity: 'Edmonton',
    distanceFromCalgary: '3 hours',
    distanceFromEdmonton: 'Various locations',
    isHidden: false,
    tips: ['Follow on social media', 'Try the brisket', 'Often at festivals']
  }
];

// Enhanced Hiking Trails with Safety Info
export const ADDITIONAL_ALBERTA_ATTRACTIONS: AlbertaAttraction[] = [
  {
    id: 'h6',
    name: 'Valley of the Five Lakes',
    location: 'Jasper National Park',
    coordinates: { lat: 52.8167, lng: -117.9833 },
    description: 'Five stunning lakes each with different colored water due to varying mineral content.',
    category: 'hiking',
    difficulty: 'easy',
    season: 'May - October',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop',
    rating: 4.6,
    priceRange: 'free',
    duration: '2-3 hours',
    features: ['Colored lakes', 'Easy trail', 'Photography', 'Family-friendly'],
    nearestCity: 'Jasper',
    distanceFromCalgary: '4 hours',
    distanceFromEdmonton: '3.5 hours',
    isHidden: true,
    dangerousAnimals: ['Black bears', 'Grizzly bears'],
    safetyWarnings: ['Stay on trail', 'Make noise in bear country'],
    tips: ['Best colors in morning light', 'Bring camera', 'Can combine with other Jasper hikes']
  },
  {
    id: 'h7',
    name: 'Sentinel Pass',
    location: 'Banff National Park',
    coordinates: { lat: 51.3167, lng: -116.2167 },
    description: 'Challenging hike with incredible views of Larch Valley and the Ten Peaks.',
    category: 'hiking',
    difficulty: 'difficult',
    season: 'July - September',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&h=300&fit=crop',
    rating: 4.8,
    priceRange: 'free',
    duration: '6-8 hours',
    features: ['Alpine views', 'Larch trees', 'High elevation', 'Challenging terrain'],
    nearestCity: 'Lake Louise',
    distanceFromCalgary: '2.5 hours',
    distanceFromEdmonton: '5 hours',
    isHidden: false,
    dangerousAnimals: ['Grizzly bears', 'Black bears'],
    safetyWarnings: ['High altitude', 'Weather changes quickly', 'Steep terrain'],
    tips: ['Start very early', 'Check weather conditions', 'Spectacular larch colors in fall']
  }
];

// Adventure Activities
export const ALBERTA_ADVENTURES: AlbertaAttraction[] = [
  {
    id: 'adv1',
    name: 'Columbia Icefield Skywalk',
    location: 'Jasper National Park',
    coordinates: { lat: 52.2167, lng: -117.2267 },
    description: 'Glass-floored observation platform extending over the Sunwapta Valley.',
    category: 'adventure',
    season: 'April - October',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop',
    rating: 4.5,
    priceRange: '$$$',
    duration: '2-3 hours',
    features: ['Glass floor', 'Valley views', 'Interpretive center', 'Glacier views'],
    nearestCity: 'Jasper',
    distanceFromCalgary: '4 hours',
    distanceFromEdmonton: '3.5 hours',
    isHidden: false,
    tips: ['Combine with glacier tour', 'Can be windy', 'Great photos']
  },
  {
    id: 'adv2',
    name: 'Whitewater Rafting - Kicking Horse River',
    location: 'Golden, BC (near Alberta border)',
    coordinates: { lat: 51.2967, lng: -116.9633 },
    description: "Thrilling whitewater rafting on one of Canada's best rafting rivers.",
    category: 'adventure',
    season: 'May - September',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop',
    rating: 4.8,
    priceRange: '$$$',
    duration: 'Half day - Full day',
    features: ['Class IV rapids', 'Scenic canyon', 'Professional guides', 'All equipment provided'],
    nearestCity: 'Golden',
    distanceFromCalgary: '3 hours',
    distanceFromEdmonton: '5.5 hours',
    isHidden: false,
    safetyWarnings: ['Strong currents', 'Cold water', 'Physical activity required'],
    tips: ['Book ahead in summer', 'Minimum age restrictions', 'Wetsuit provided']
  }
];

// Fishing Spots
export const ALBERTA_FISHING_SPOTS: AlbertaAttraction[] = [
  {
    id: 'fish1',
    name: 'Bow River - Calgary',
    location: 'Calgary',
    coordinates: { lat: 51.0447, lng: -114.0719 },
    description: 'World-class urban trout fishing right in downtown Calgary. Famous for large brown and rainbow trout.',
    category: 'fishing',
    difficulty: 'easy',
    season: 'Year-round',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&h=300&fit=crop',
    rating: 4.8,
    priceRange: '$',
    duration: '2-8 hours',
    features: ['Urban fishing', 'Large trout', 'Fly fishing', 'Year-round access'],
    nearestCity: 'Calgary',
    distanceFromCalgary: '0 km',
    distanceFromEdmonton: '3 hours',
    isHidden: false,
    tips: ['Fishing license required', 'Best spots near weirs', 'Catch and release encouraged']
  },
  {
    id: 'fish2',
    name: 'Pyramid Lake',
    location: 'Jasper National Park',
    coordinates: { lat: 52.9167, lng: -118.0833 },
    description: 'Pristine mountain lake with excellent lake trout and mountain whitefish fishing.',
    category: 'fishing',
    difficulty: 'easy',
    season: 'June - October',
    image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=400&h=300&fit=crop',
    rating: 4.6,
    priceRange: '$',
    duration: '3-6 hours',
    features: ['Mountain lake', 'Lake trout', 'Scenic setting', 'Boat rentals'],
    nearestCity: 'Jasper',
    distanceFromCalgary: '4 hours',
    distanceFromEdmonton: '3.5 hours',
    isHidden: true,
    dangerousAnimals: ['Black bears', 'Grizzly bears'],
    tips: ['Boat fishing most productive', 'Early morning best', 'National park license required']
  },
  {
    id: 'fish3',
    name: 'Oldman River',
    location: 'Southern Alberta',
    coordinates: { lat: 49.7000, lng: -113.8000 },
    description: 'Premier fly fishing destination with native bull trout and cutthroat trout in pristine waters.',
    category: 'fishing',
    difficulty: 'moderate',
    season: 'June - October',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&h=300&fit=crop',
    rating: 4.9,
    priceRange: 'free',
    duration: '4-8 hours',
    features: ['Native trout', 'Fly fishing', 'Pristine waters', 'Remote access'],
    nearestCity: 'Pincher Creek',
    distanceFromCalgary: '2.5 hours',
    distanceFromEdmonton: '5 hours',
    isHidden: true,
    dangerousAnimals: ['Grizzly bears', 'Black bears', 'Cougars'],
    safetyWarnings: ['Remote location', 'Swift current', 'Wildlife area'],
    tips: ['Barbless hooks only', 'Catch and release', 'Wading can be challenging']
  },
  {
    id: 'fish4',
    name: 'Crowsnest River',
    location: 'Crowsnest Pass',
    coordinates: { lat: 49.6333, lng: -114.4833 },
    description: 'Clear, cold freestone river famed for abundant rainbow and brown trout. Classic dry-fly water.',
    category: 'fishing',
    difficulty: 'moderate',
    season: 'June - October',
    image: 'https://images.unsplash.com/photo-1508186225823-0963cf9ab0de?w=400&h=300&fit=crop',
    rating: 4.9,
    priceRange: 'free',
    duration: '4-8 hours',
    features: ['Dry-fly fishing', 'Rainbow trout', 'Public access', 'Wadeable runs'],
    nearestCity: 'Blairmore',
    distanceFromCalgary: '2.5 hours',
    distanceFromEdmonton: '5 hours',
    isHidden: true,
    dangerousAnimals: ['Black bears', 'Cougars'],
    safetyWarnings: ['Cold water', 'Uneven wading'],
    tips: ['Barbless hooks', 'Match the hatch mid-summer']
  },
  {
    id: 'fish5',
    name: 'Upper Red Deer River',
    location: 'Ya Ha Tinda / Sundre region',
    coordinates: { lat: 51.7000, lng: -115.1000 },
    description: 'Wild mountain section with cutthroat and bull trout; scenic meadows and canyon stretches.',
    category: 'fishing',
    difficulty: 'moderate',
    season: 'June - September',
    image: 'https://images.unsplash.com/photo-1472148439583-1f712ed1779e?w=400&h=300&fit=crop',
    rating: 4.7,
    priceRange: 'free',
    duration: '4-8 hours',
    features: ['Cutthroat trout', 'Meadow beats', 'Canyon pools', 'Scenic'],
    nearestCity: 'Sundre',
    distanceFromCalgary: '2.5 hours',
    distanceFromEdmonton: '3.5 hours',
    isHidden: true,
    dangerousAnimals: ['Grizzly bears', 'Black bears'],
    safetyWarnings: ['Remote access', 'Variable flows'],
    tips: ['Carry bear spray', 'Best fished on foot with light tackle']
  },
  {
    id: 'fish6',
    name: 'Maligne Lake Outlet (Maligne River)',
    location: 'Jasper National Park',
    coordinates: { lat: 52.7239, lng: -117.6476 },
    description: 'Productive sections near the outlet with rainbows and brookies; stunning scenery.',
    category: 'fishing',
    difficulty: 'easy',
    season: 'July - September',
    image: 'https://images.unsplash.com/photo-1466220666686-90bdba318c7e?w=400&h=300&fit=crop',
    rating: 4.6,
    priceRange: '$',
    duration: '3-6 hours',
    features: ['Rainbow trout', 'Brook trout', 'Easy access', 'National park setting'],
    nearestCity: 'Jasper',
    distanceFromCalgary: '4.5 hours',
    distanceFromEdmonton: '3.5 hours',
    isHidden: false,
    dangerousAnimals: ['Black bears', 'Elk'],
    tips: ['Parks Canada fishing permit required', 'Single barbless hooks']
  }
];

export const ALL_ADDITIONAL_ATTRACTIONS = [
  ...ALBERTA_WATERFALLS,
  ...ALBERTA_BIRDWATCHING_SPOTS,
  ...ALBERTA_HIDDEN_WATERS,
  ...ALBERTA_FOOD_TRUCKS,
  ...ADDITIONAL_ALBERTA_ATTRACTIONS,
  ...ALBERTA_ADVENTURES,
  ...ALBERTA_FISHING_SPOTS
];