import { AlbertaAttraction } from './alberta-attractions';

export const ADDITIONAL_ALBERTA_ATTRACTIONS: AlbertaAttraction[] = [
  // More Hiking Trails
  {
    id: 'h6',
    name: 'Valley of the Five Lakes',
    location: 'Jasper National Park',
    coordinates: { lat: 52.8167, lng: -117.9833 },
    description: 'Five stunning lakes each with different colored water due to varying mineral content.',
    category: 'hiking',
    difficulty: 'easy',
    season: 'May - October',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop',
    rating: 4.6,
    priceRange: 'free',
    duration: '2-3 hours',
    features: ['Colored lakes', 'Easy trail', 'Photography', 'Family-friendly'],
    nearestCity: 'Jasper',
    distanceFromCalgary: '4 hours',
    distanceFromEdmonton: '3.5 hours',
    isHidden: true,
    tips: ['Best colors in morning light', 'Bring camera', 'Can combine with other Jasper hikes']
  },
  {
    id: 'h7',
    name: 'Sentinel Pass',
    location: 'Banff National Park',
    coordinates: { lat: 51.3167, lng: -116.2167 },
    description: 'Challenging hike with incredible views of Larch Valley and the Ten Peaks.',
    category: 'hiking',
    difficulty: 'difficult',
    season: 'July - September',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&h=300&fit=crop',
    rating: 4.8,
    priceRange: 'free',
    duration: '6-8 hours',
    features: ['Alpine views', 'Larch trees', 'High elevation', 'Challenging terrain'],
    nearestCity: 'Lake Louise',
    distanceFromCalgary: '2.5 hours',
    distanceFromEdmonton: '5 hours',
    isHidden: false,
    tips: ['Start very early', 'Check weather conditions', 'Spectacular larch colors in fall']
  },

  // More Hot Springs
  {
    id: 'hs4',
    name: 'Banff Upper Hot Springs',
    location: 'Banff National Park',
    coordinates: { lat: 51.1667, lng: -115.5667 },
    description: 'Historic hot springs with stunning mountain views and modern facilities.',
    category: 'hotspring',
    season: 'Year-round',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&h=300&fit=crop',
    rating: 4.3,
    priceRange: '$$',
    duration: '2-3 hours',
    features: ['Historic site', 'Mountain views', 'Modern facilities', 'Gift shop'],
    nearestCity: 'Banff',
    distanceFromCalgary: '1.5 hours',
    distanceFromEdmonton: '4.5 hours',
    isHidden: false,
    tips: ['Can get crowded', 'Rent towels and swimsuits', 'Great after hiking']
  },

  // More Hidden Gems
  {
    id: 'hg5',
    name: 'Dinosaur Provincial Park',
    location: 'Brooks',
    coordinates: { lat: 50.7667, lng: -111.5167 },
    description: 'UNESCO World Heritage Site with incredible dinosaur fossils and badlands scenery.',
    category: 'hidden-gem',
    season: 'April - October',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop',
    rating: 4.6,
    priceRange: '$',
    duration: 'Full day',
    features: ['Dinosaur fossils', 'Badlands', 'Guided tours', 'Camping'],
    nearestCity: 'Brooks',
    distanceFromCalgary: '2.5 hours',
    distanceFromEdmonton: '4 hours',
    isHidden: true,
    tips: ['Book fossil tours ahead', 'Bring sun protection', 'Great for kids']
  },

  // More Cycling
  {
    id: 'c3',
    name: 'Legacy Trail',
    location: 'Banff to Canmore',
    coordinates: { lat: 51.1167, lng: -115.4167 },
    description: 'Paved multi-use trail connecting Banff and Canmore with mountain views.',
    category: 'cycling',
    difficulty: 'easy',
    season: 'April - October',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop',
    rating: 4.7,
    priceRange: 'free',
    duration: '2-4 hours',
    features: ['Paved trail', 'Mountain views', 'Wildlife viewing', 'Family-friendly'],
    nearestCity: 'Banff/Canmore',
    distanceFromCalgary: '1.5 hours',
    distanceFromEdmonton: '4.5 hours',
    isHidden: false,
    tips: ['Bike rentals available in both towns', 'Watch for wildlife', 'Can be busy on weekends']
  },

  // Walking Trails
  {
    id: 'w1',
    name: 'Fenlands Trail',
    location: 'Banff National Park',
    coordinates: { lat: 51.1833, lng: -115.5667 },
    description: 'Easy boardwalk trail through wetlands with mountain views and wildlife.',
    category: 'walking',
    difficulty: 'easy',
    season: 'May - October',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&h=300&fit=crop',
    rating: 4.3,
    priceRange: 'free',
    duration: '1 hour',
    features: ['Boardwalk', 'Wetlands', 'Wildlife viewing', 'Accessible'],
    nearestCity: 'Banff',
    distanceFromCalgary: '1.5 hours',
    distanceFromEdmonton: '4.5 hours',
    isHidden: false,
    tips: ['Great for bird watching', 'Wheelchair accessible', 'Early morning best for wildlife']
  }
];

// Adventure Activities
export const ALBERTA_ADVENTURES: AlbertaAttraction[] = [
  {
    id: 'adv1',
    name: 'Columbia Icefield Skywalk',
    location: 'Jasper National Park',
    coordinates: { lat: 52.2167, lng: -117.2267 },
    description: 'Glass-floored observation platform extending over the Sunwapta Valley.',
    category: 'adventure',
    season: 'April - October',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop',
    rating: 4.5,
    priceRange: '$$$',
    duration: '2-3 hours',
    features: ['Glass floor', 'Valley views', 'Interpretive center', 'Glacier views'],
    nearestCity: 'Jasper',
    distanceFromCalgary: '4 hours',
    distanceFromEdmonton: '3.5 hours',
    isHidden: false,
    tips: ['Combine with glacier tour', 'Can be windy', 'Great photos']
  },
  {
    id: 'adv2',
    name: 'Whitewater Rafting - Kicking Horse River',
    location: 'Golden, BC (near Alberta border)',
    coordinates: { lat: 51.2967, lng: -116.9633 },
    description: 'Thrilling whitewater rafting on one of Canada\'s best rafting rivers.',
    category: 'adventure',
    season: 'May - September',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop',
    rating: 4.8,
    priceRange: '$$$',
    duration: 'Half day - Full day',
    features: ['Class IV rapids', 'Scenic canyon', 'Professional guides', 'All equipment provided'],
    nearestCity: 'Golden',
    distanceFromCalgary: '3 hours',
    distanceFromEdmonton: '5.5 hours',
    isHidden: false,
    tips: ['Book ahead in summer', 'Minimum age restrictions', 'Wetsuit provided']
  }
];

// Fishing Spots
export const ALBERTA_FISHING_SPOTS: AlbertaAttraction[] = [
  {
    id: 'fish1',
    name: 'Bow River - Calgary',
    location: 'Calgary',
    coordinates: { lat: 51.0447, lng: -114.0719 },
    description: 'World-class urban trout fishing right in downtown Calgary. Famous for large brown and rainbow trout.',
    category: 'hidden-gem',
    difficulty: 'easy',
    season: 'Year-round',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&h=300&fit=crop',
    rating: 4.8,
    priceRange: '$',
    duration: '2-8 hours',
    features: ['Urban fishing', 'Large trout', 'Fly fishing', 'Year-round access'],
    nearestCity: 'Calgary',
    distanceFromCalgary: '0 km',
    distanceFromEdmonton: '3 hours',
    isHidden: false,
    tips: ['Fishing license required', 'Best spots near weirs', 'Catch and release encouraged']
  },
  {
    id: 'fish2',
    name: 'Pyramid Lake',
    location: 'Jasper National Park',
    coordinates: { lat: 52.9167, lng: -118.0833 },
    description: 'Pristine mountain lake with excellent lake trout and mountain whitefish fishing.',
    category: 'hidden-gem',
    difficulty: 'easy',
    season: 'June - October',
    image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=400&h=300&fit=crop',
    rating: 4.6,
    priceRange: '$',
    duration: '3-6 hours',
    features: ['Mountain lake', 'Lake trout', 'Scenic setting', 'Boat rentals'],
    nearestCity: 'Jasper',
    distanceFromCalgary: '4 hours',
    distanceFromEdmonton: '3.5 hours',
    isHidden: true,
    tips: ['Boat fishing most productive', 'Early morning best', 'National park license required']
  },
  {
    id: 'fish3',
    name: 'Oldman River',
    location: 'Southern Alberta',
    coordinates: { lat: 49.7000, lng: -113.8000 },
    description: 'Premier fly fishing destination with native bull trout and cutthroat trout in pristine waters.',
    category: 'hidden-gem',
    difficulty: 'moderate',
    season: 'June - October',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&h=300&fit=crop',
    rating: 4.9,
    priceRange: 'free',
    duration: '4-8 hours',
    features: ['Native trout', 'Fly fishing', 'Pristine waters', 'Remote access'],
    nearestCity: 'Pincher Creek',
    distanceFromCalgary: '2.5 hours',
    distanceFromEdmonton: '5 hours',
    isHidden: true,
    tips: ['Barbless hooks only', 'Catch and release', 'Wading can be challenging']
  },
  {
    id: 'fish4',
    name: 'Lake Minnewanka',
    location: 'Banff National Park',
    coordinates: { lat: 51.2167, lng: -115.5167 },
    description: 'Large mountain reservoir with lake trout, whitefish, and northern pike. Boat fishing paradise.',
    category: 'hidden-gem',
    difficulty: 'easy',
    season: 'May - October',
    image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=400&h=300&fit=crop',
    rating: 4.5,
    priceRange: '$$',
    duration: '3-8 hours',
    features: ['Large lake trout', 'Boat rentals', 'Mountain scenery', 'Multiple species'],
    nearestCity: 'Banff',
    distanceFromCalgary: '1.5 hours',
    distanceFromEdmonton: '4.5 hours',
    isHidden: false,
    tips: ['Boat fishing recommended', 'Deep water trolling', 'Scenic boat tours available']
  },
  {
    id: 'fish5',
    name: 'Red Deer River',
    location: 'Central Alberta',
    coordinates: { lat: 52.2681, lng: -113.8112 },
    description: 'Excellent walleye and northern pike fishing with easy access and good facilities.',
    category: 'hidden-gem',
    difficulty: 'easy',
    season: 'May - October',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&h=300&fit=crop',
    rating: 4.4,
    priceRange: 'free',
    duration: '2-6 hours',
    features: ['Walleye fishing', 'Northern pike', 'Easy access', 'Shore fishing'],
    nearestCity: 'Red Deer',
    distanceFromCalgary: '1.5 hours',
    distanceFromEdmonton: '1.5 hours',
    isHidden: false,
    tips: ['Good shore fishing spots', 'Jigs and minnows work well', 'Check regulations']
  },
  {
    id: 'fish6',
    name: 'Athabasca River',
    location: 'Jasper National Park',
    coordinates: { lat: 52.8833, lng: -118.0833 },
    description: 'Large river system with mountain whitefish, bull trout, and arctic grayling in pristine wilderness.',
    category: 'hidden-gem',
    difficulty: 'moderate',
    season: 'June - September',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&h=300&fit=crop',
    rating: 4.7,
    priceRange: 'free',
    duration: '3-8 hours',
    features: ['Arctic grayling', 'Bull trout', 'Wilderness setting', 'Fly fishing'],
    nearestCity: 'Jasper',
    distanceFromCalgary: '4 hours',
    distanceFromEdmonton: '3.5 hours',
    isHidden: true,
    tips: ['Barbless hooks required', 'Catch and release', 'Waders recommended']
  },
  {
    id: 'fish7',
    name: 'Ghost Lake',
    location: 'Kananaskis Country',
    coordinates: { lat: 51.0500, lng: -114.9500 },
    description: 'Hidden mountain lake with excellent brook trout fishing and stunning Rocky Mountain views.',
    category: 'hidden-gem',
    difficulty: 'moderate',
    season: 'June - September',
    image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=400&h=300&fit=crop',
    rating: 4.6,
    priceRange: 'free',
    duration: '4-8 hours',
    features: ['Brook trout', 'Mountain lake', 'Scenic hiking', 'Remote location'],
    nearestCity: 'Canmore',
    distanceFromCalgary: '2 hours',
    distanceFromEdmonton: '5 hours',
    isHidden: true,
    tips: ['Hike required to access', 'Small flies work best', 'Beautiful mountain setting']
  },
  {
    id: 'fish8',
    name: 'North Saskatchewan River',
    location: 'Edmonton',
    coordinates: { lat: 53.5444, lng: -113.4909 },
    description: 'Urban river fishing for walleye, northern pike, and goldeye right in the city.',
    category: 'hidden-gem',
    difficulty: 'easy',
    season: 'May - October',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&h=300&fit=crop',
    rating: 4.2,
    priceRange: 'free',
    duration: '2-6 hours',
    features: ['Urban fishing', 'Multiple species', 'Easy access', 'Shore fishing'],
    nearestCity: 'Edmonton',
    distanceFromCalgary: '3 hours',
    distanceFromEdmonton: '0 km',
    isHidden: false,
    tips: ['Good access points throughout city', 'Evening fishing productive', 'Check water levels']
  },
  {
    id: 'fish9',
    name: 'Maligne Lake',
    location: 'Jasper National Park',
    coordinates: { lat: 52.6667, lng: -117.9667 },
    description: 'Largest natural lake in Canadian Rockies with excellent lake trout and brook trout fishing.',
    category: 'hidden-gem',
    difficulty: 'easy',
    season: 'June - October',
    image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=400&h=300&fit=crop',
    rating: 4.8,
    priceRange: '$$',
    duration: '4-8 hours',
    features: ['Largest natural lake', 'Lake trout', 'Boat rentals', 'Scenic beauty'],
    nearestCity: 'Jasper',
    distanceFromCalgary: '4.5 hours',
    distanceFromEdmonton: '4 hours',
    isHidden: false,
    tips: ['Boat fishing most effective', 'Trolling for lake trout', 'Combine with sightseeing']
  },
  {
    id: 'fish10',
    name: 'Crowsnest River',
    location: 'Southern Alberta',
    coordinates: { lat: 49.6333, lng: -114.4500 },
    description: 'Premier fly fishing stream with native cutthroat and bull trout in the foothills.',
    category: 'hidden-gem',
    difficulty: 'moderate',
    season: 'June - October',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&h=300&fit=crop',
    rating: 4.7,
    priceRange: 'free',
    duration: '3-8 hours',
    features: ['Native cutthroat', 'Bull trout', 'Fly fishing', 'Foothills setting'],
    nearestCity: 'Blairmore',
    distanceFromCalgary: '2 hours',
    distanceFromEdmonton: '4.5 hours',
    isHidden: true,
    tips: ['Dry flies effective', 'Respect private property', 'Catch and release']
  }
];

export const ALL_ADDITIONAL_ATTRACTIONS = [
  ...ADDITIONAL_ALBERTA_ATTRACTIONS,
  ...ALBERTA_ADVENTURES,
  ...ALBERTA_FISHING_SPOTS
];